--- # install and configure IIS in a windows 10 host/node
- hosts: win10
  
  tasks:
  
  - name: create directory 
    win_file:
        path: C:\tmpfiles\net472
        state: directory
  
  - name: Download Microsoft .NET Framework 4.7.2 installer
    win_get_url:
        url: "https://dotnet.microsoft.com/download/thank-you/net472"
        dest: C:\tmpfiles\net472

  - name: Run Microsoft .NET Framework 4.7.2 installer  
    win_command: .\NDP472-KB4054531-Web.exe
    args:
        chdir: C:\tmpfiles\net472   
             