---
- hosts: qa03
  vars:
    staging_path: C:\inetpub\wwwroot\ansibledeployments  
    webservice_folder_path: "{{ staging_path }}\\Webservices"
    webportal_folder_path: "{{ staging_path }}\\Webportals"    
    
  tasks: 

  - name: create directory 
    win_file:
       path: "{{ staging_path }}"
       state: directory    
    
  - name: create directory 
    win_file:
       path: "{{ webservice_folder_path }}"
       state: directory 

  - name: create directory 
    win_file:
       path: "{{ webportal_folder_path }}"
       state: directory        

  - name: Download artifacts to the windows node      
    win_get_url:
       url: "ftp://ftp.box.com/Releases/CoreWebServices/{{ branch_name }}/CoreAutoUpdates-{{ Web_service_app_version }}.7z"
       dest: "{{ staging_path }}\\"
       url_username: updates@wheygroup.com
       url_password: Abcd123* 
 
  - name: Download artifacts to the windows node      
    win_get_url:
       url: "ftp://ftp.box.com/Releases/WebPortals/{{ branch_name }}/WebPortalsAutoUpdate-{{ Web_site_app_version }}.7z"
       dest: "{{ staging_path }}\\"
       url_username: updates@wheygroup.com
       url_password: Abcd123* 
 
  - name: Unzip the downloaded artifact file
    win_unzip:
        src: "{{ staging_path }}\\CoreAutoUpdates-{{ Web_service_app_version }}.7z"   
        dest: "{{ staging_path }}\\CoreAutoUpdates-{{ Web_service_app_version }}"
        delete_archive: True   
        recurse: True         

  - name: Unzip the downloaded artifact file
    win_unzip:
        src: "{{ staging_path }}\\WebPortalsAutoUpdate-{{ Web_site_app_version }}.7z"   
        dest: "{{ staging_path }}\\WebPortalsAutoUpdate-{{ Web_site_app_version }}" 
        recurse: yes
        delete_archive: True        
    
  - name: copy directory
    win_copy:
        src: "{{ staging_path }}\\CoreAutoUpdates-{{ Web_service_app_version }}\\CoreAutoUpdates-{{ Web_service_app_version }}\\WebSite"
        dest: "{{ webservice_folder_path }}"
        remote_src: True
        
  - name: copy directory
    win_copy:
        src: "{{ staging_path }}\\WebPortalsAutoUpdate-{{ Web_site_app_version }}\\WebPortalsAutoUpdate\\WebSite"
        dest: "{{ webportal_folder_path }}"  
        remote_src: True                       
        
  - name: Remove directory
    win_file:
        path: "{{ staging_path }}\\CoreAutoUpdates-{{ Web_service_app_version }}"    
        state: absent   

  - name: Remove directory
    win_file:
        path: "{{ staging_path }}\\WebPortalsAutoUpdate-{{ Web_site_app_version }}"    
        state: absent           