---
- hosts: win10
  vars:
    ansible_site_path: 
    staging_path: D:\deploy
      
    
  tasks:  
           
  - name: Download artifacts to the windows node      
    win_get_url:
       url: "ftp://ftp.box.com/Releases/CoreWebServices/{{ branch_name }}/CoreAutoUpdates-{{ app_version }}.7z"
       dest: "{{ staging_path }}\\"
       url_username: updates@wheygroup.com
       url_password: Abcd123*
 
  - name: Unzip the downloaded artifact file
    win_unzip:
        src: "{{ staging_path }}\\CoreAutoUpdates-{{ app_version }}.7z"   
        dest: "{{ staging_path }}\\CoreAutoUpdates-{{ app_version }}"         
    