---
- hosts: qa03
  vars:
    staging_path: C:\townsuite_deploy
  tasks:
  
  - name: create directory 
    win_file:
       path: "{{ staging_path }}"
       state: directory       
  
  - name: Copying IIS installing PS1 to windows server
    win_copy: 
       src: /var/lib/awx/projects/_14__firstproject_amila/iis_install.ps1
       dest: "{{ staging_path }}\\"
         
  - name: Installing IIS with powershell script
    win_shell: .\iis_install.ps1
    args:
        chdir: "{{ staging_path }}"
     
