---
- hosts: win10
  vars:
    staging_path: C:\inetpub\wwwroot\ansibledeployments\Webservices\WebSite
    staging_path_1: C:\inetpub\wwwroot\ansibledeployments\Webportals\WebSite 
  tasks:

 # - name: Copy webconfig files 
  #  win_copy:
   #     src: ""
    #    dest: ""
     #   remote_src: True
  
  - name: Create App Pool with .NET 4.0
    win_iis_webapppool:
      name: Webservice8087
      state: started
      attributes: 
         managedRuntimeVersion: v4.0     
     
  # - name: Import a certificate
    # win_certificate_store:
      # path: C:\Temp\cert.pem
      # state: present
      
  - name: Add a HTTPS binding
    win_iis_webbinding:
      name: Webservice8087
      protocol: https
      port: 8087
      hostname: localhost
      certificate_hash: a373a5ce2467e3b565825446e48e0bf416c72488
      state: present 

  - name: create new website
    win_iis_website:
      name: Webservice8087
      state: started 
      physical_path: "{{ staging_path }}"
      port: 8087
      hostname:        
          
  - name: Restart an application pool
    win_iis_webapppool:
      name: Webservice8087
      state: restarted  
     
  - name: Create App Pool with .NET 4.0
    win_iis_webapppool:
      name: Webportals8088
      state: started
      attributes: 
         managedRuntimeVersion: v4.0  
      
  - name: Webportals IIS site creation
    win_iis_website:
      name: 'Webportals8088'
      state: started
      port: 8088
      ip: 
      hostname: localhost
      application_pool: 'Webportals8088'
      physical_path: "{{ staging_path_1 }}"  
      ssl: false     
      
  - name: Restart an application pool
    win_iis_webapppool:
      name: Webportals8088
      state: restarted     
      
   