---
- hosts: win10
  vars:
    staging_path: C:\inetpub\wwwroot\ansibledeployments\Webservices\WebSite
  tasks:

  - name: App Pool with .NET 4.0
    win_iis_webapppool:
      name: Webservice8087
      state: started
      attributes: managedRuntimeVersion:v4.0
    
  
  - name: Webportals IIS site creation
    win_iis_website:
      name: 'Webservice8087'
      state: started
      port: 8087
      ip: 127.0.0.1
      hostname: 
      application_pool: 'Webservice8087'
      physical_path: "{{ staging_path }}"  
      ssl: true      
   
      
  - name: Restart an application pool
    win_iis_webapppool:
      name: 'Webservice8087'
      state: restart  

      